name: waves
version: 1.0.0
config-version: 2

profile: waves

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  waves:
    +materialized: table

