name: duckdb_pipeline
version: "1.0"
config-version: 2
profile: default

model-paths: ["models"]

models:

  duckdb_pipeline:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: table
      +schema: stg_open_meteo
    intermediate:
      +materialized: table
      +schema: int_open_meteo
    presentation:
      +materialized: table
      +schema: open_meteo