default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: ../data/transformed.duckdb
      schema: dbt
      threads: 4
      attach:
        - path: ../data/raw.duckdb
          alias: raw    
