default:
  target: motherduck
  outputs:
    duckdb:
      type: duckdb
      path: ../data/transformed.duckdb
      schema: dbt
      threads: 4
      attach:
        - path: ../data/raw.duckdb
          alias: raw    

    motherduck:
      type: duckdb
      path: md:transformed
      schema: dbt
      threads: 4
      extensions: [motherduck]
      attach:
        - path: "md:raw"
          alias: raw     
