waves:
  target: motherduck
  outputs:
    duckdb:
      type: duckdb
      path: ./data/waves.duckdb
      schema: waves
      threads: 4

    motherduck:
      type: duckdb
      path: md:waves
      schema: waves
      threads: 4

